create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content1 text not null,
  content2 text not null,
  user_id uuid not null references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
