create table public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique
);

insert into public.roles (id, name) values
  (1, 'creator'),
  (2, 'subscriber');
